export const SAFETY_KEYWORDS = [
  'accident',
  'near miss',
  'presqu accident',
  'chute',
  'blessure',
  'blesse',
  'incendie',
  'feu',
  'fumee',
  'electrique',
  'electrocution',
  'danger',
  'urgence',
  'eboulement',
  'effondrement',
  'coincement',
  'ecrasement',
  'fracture',
] as const;
